fix build on macos.
Signed-off-by: Schspa Shi <schspa@gmail.com>

diff --git a/init_example/Makefile b/init_example/Makefile
--- a/init_example/Makefile
+++ b/init_example/Makefile
@@ -8,6 +8,23 @@ ifeq ($(DEBUG),1)
 CFLAGS+= -g
 endif
 
+# try-run
+# Usage: option = $(call try-run, $(CC)...-o "$$TMP",option-ok,otherwise)
+# Exit code chooses option. "$$TMP" serves as a temporary file and is
+# automatically cleaned up.
+try-run = $(shell set -e;		\
+	TMP=$(TMPOUT)/tmp;		\
+	TMPO=$(TMPOUT)/tmp.o;		\
+	mkdir -p $(TMPOUT);		\
+	trap "rm -rf $(TMPOUT)" EXIT;	\
+	if ($(1)) >/dev/null 2>&1;	\
+	then echo "$(2)";		\
+	else echo "$(3)";		\
+	fi)
+
+is_gnu_linux = $(call try-run, test $OSTYPE = linux-gnu,1,0)
+
+ifeq ($(is_gnu_linux),1)
 $(OUT): $(OBJS)
 	$(CROSS)$(CC) $^ -o $@ $(LDFLAGS)
 %.o: %.c
@@ -16,3 +33,7 @@ $(OUT): $(OBJS)
 .PHONY: clean
 clean:
 	-rm -rf $(OBJS) $(OUT)
+else
+All:
+	echo "Skip for non-gnu system"
+endif
